### ISSUE TITLE
Could not pass event InventoryCreativeEvent to UReport v4.8

### ISSUE THREAD

**Issue by mostm** [AlaDyn172/UReport#3]
Hello, i'm recently installed UReport on my Server, and getting this error in console, every time that something in player's creative inventory is changed:
```
[20:29:36 ERROR]: Could not pass event InventoryCreativeEvent to UReport v4.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[core.jar:git-Spigot-325fbc7-dc7d31b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[core.jar:git-Spigot-325fbc7-dc7d31b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2045) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [core.jar:git-Spigot-325fbc7-dc7d31b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at me.AlaDyn172.UReport.Main.onClickItem(Main.java:325) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[core.jar:git-Spigot-325fbc7-dc7d31b]
        ... 15 more
```
Plugin works perfectly, but i don't want to see these errors, so please, fix them up

**Comment by AlaDyn172** [comment]
Hello,

Happy New Year 2019  👍 
If you still use the plugin, check out the new version!
